'use client';

import Link from 'next/link';
import React from 'react';

const Register = () => {
  return (
    <div className="login">
      <section>
        <form action="">
          <input placeholder="Enter Name" type="text" />
          <input placeholder="Enter Email" type="email" />
          <input placeholder="Enter Password" type="password" />
          <button type="submit">Register</button>
          <p>OR</p>
          <Link href={'/login'}>Already have an account? Login</Link>
        </form>
      </section>
    </div>
  );
};

// export const metadata = {
//   title: 'Register',
//   description: 'Generated by create next app',
// };

export default Register;
