'use client';

import axios from 'axios';
import Link from 'next/link';
import React, { useContext, useState } from 'react';
import toast from 'react-hot-toast';
import { Context } from '../../components/Clients';
import { redirect } from 'next/navigation';

const Login = () => {
  const [data, setdata] = useState({
    email: '',
    password: '',
  });

  const { user, setuser } = useContext(Context);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setdata({
      ...data,
      [name]: value,
    });
  };

  const handleSubmitLogin = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('/api/auth/login', data);
      toast.success(response.data.message);
      setuser(response.data.data);
    } catch (error) {
      toast.error(error?.response?.data?.message);
    }
  };
  if (user?._id) return redirect('/');

  return (
    <div className="login">
      <section>
        <form onSubmit={handleSubmitLogin}>
          <input
            onChange={handleChange}
            name="email"
            value={data.email}
            placeholder="Enter Email"
            type="email"
          />
          <input
            onChange={handleChange}
            name="password"
            value={data.password}
            placeholder="Enter Password"
            type="password"
          />
          <button type="submit">Login</button>
          <p>OR</p>
          <Link href={'/register'}>New User</Link>
        </form>
      </section>
    </div>
  );
};

// export const metadata = {
//   title: 'Login',
//   description: 'Generated by create next app',
// };

export default Login;
