'use client';

import Link from 'next/link';
import React from 'react';

const Login = () => {
  return (
    <div className="login">
      <section>
        <form action="">
          <input placeholder="Enter Email" type="email" />
          <input placeholder="Enter Password" type="password" />
          <button type="submit">Login</button>
          <p>OR</p>
          <Link href={'/register'}>New User</Link>
        </form>
      </section>
    </div>
  );
};

// export const metadata = {
//   title: 'Login',
//   description: 'Generated by create next app',
// };

export default Login;
